### ISSUE TITLE
No "vertices" table when there are no vertex attributes

### ISSUE THREAD

**Issue by erbenpeter** [lynxkite/lynxkite#119]
The `vertices` table does not exist, but the `edges` table does.

![sql-on-networkit-graph](https://user-images.githubusercontent.com/3944870/102452433-a37b9c00-403a-11eb-8ffe-ad2fd64cb939.png)

My first guess is that the "Create Erdős–Rényi graph" operation runs outside the Spark domain (I'm not sure it's the correct terminology), so the `vertices` table is not created automatically for the Spark SQL version.

After running an edge attribute computation, the `edges` table is created properly and I can run SQL on it.

![edges-of-networkit-graph](https://user-images.githubusercontent.com/3944870/102452179-38ca6080-403a-11eb-82f9-78b1722e84c5.png)

If I add a "Compute degree" operation, the `vertices` table appears.

**Comment by erbenpeter** [comment]
After some thinking: maybe it's just that the SQL always fails when there are no vertex attributes?

And the "traditional" graph creation operations always create at least one attribute?

If that's the case then maybe some error handling in the SQL box would be useful.

**Comment by darabos** [comment]
Thanks for the report!

> After some thinking: maybe it's just that the SQL always fails when there are no vertex attributes?

Yeah, looks that way. If you create an example graph and discard all vertex attributes, you get the same error on SQL. It's not the fault of the Erdős–Rényi graph or dispersion.

> If that's the case then maybe some error handling in the SQL box would be useful.

Absolutely! We should add an extra `assert` for this. Also for the `edge_attributes` table when there are no edge attributes.
