### ISSUE TITLE
Cannot retrieve box metadata. The ID attribute parameter must be set.

### ISSUE THREAD

**Issue by estrelleDS** [lynxkite/lynxkite#163]
I cannot get the metadata while trying  to visualize data in lynxkite

**Comment by darabos** [comment]
Hi!
Based on the error I would say you are using a "Use table as vertex/edge attribute" box and didn't set the "ID attribute" parameter. This box has to "join" a table to the graph. So it needs to know the name of the key in the graph (the "ID attribute" parameter) and in the table (the "ID column" parameter).

![image](https://user-images.githubusercontent.com/1268018/113759669-a1d30280-9715-11eb-9a92-417f4f714a9c.png)

https://github.com/lynxkite/lynxkite/blob/4.2.0/app/com/lynxanalytics/biggraph/frontend_operations/VertexAttributeOperations.scala#L45

If this is not the case, can you tell me more about the context where you get this error? A screenshot of the workspace is great. Or you can select all the relevant boxes and press Ctrl-C to copy them to the clipboard as YAML. Then copy them here or on https://gist.github.com/.

**Comment by estrelleDS** [comment]
Hi @darabos 

You were right!!! I had not set the parameters. Thanks
