### ISSUE TITLE
csv file upload failed lynxkite

### ISSUE THREAD

**Issue by myrasika** [lynxkite/lynxkite#185]
details: {}
message: File upload failed.
url: >-
  https://demo.lynxkite.com/user/a@gmail.com/lk/#/workspace/Users/a@gmail.com/r_net
version: |
  LynxKite Enterprise 4.2.2

**Comment by darabos** [comment]
Hi Myra,
The demo instances are fairly small and the upload size is limited. You can upload a Gzipped file to possibly get under the size limit. But if you want to use LynxKite with really big data, you will have to run your own instance. It's fairly easy to run even on a laptop. See https://lynxkite.com/getting-started#docker-linux. Let me know if you need help!

**Comment by myrasika** [comment]
@darabos  I was using the cloud version and figured out it was because of the file size, since it was accepting smaller file sizes but uploading the same file to the pc version it works without zipping.

**Comment by tuckging** [comment]
![image](https://user-images.githubusercontent.com/9315500/175053239-503f8a4e-7af8-4b7a-8ab3-60229d55e576.png)

While it makes sense to limit file upload sizes, I think that the error message can be more helpful 😅  I will make a PR for this some day
