### ISSUE TITLE
Option for weighing by edges at the "weighted aggregate on neighbours function"

### ISSUE THREAD

**Issue by mszel** [lynxkite/lynxkite#230]
Dear LK Developers, 

It would be nice to add the option of weighting the node values by the edges at the weighted aggregate on neighbors function. I have a workaround (create a vertex feature from the edge-weight and use that as a weight), but it would be more comfortable to have the option as well.

Thank you.

Best Regards,
Marton

**Comment by lacca0** [comment]
@mszel Hi Marton!
1. Could you please specify the desired behavior in the case when a node has edges with different weights? In your workaround it seems that you are losing information.
2. How should we deal with the case when two nodes are connected with several edges simultaneously? 
3. Do we need separate cases for outcoming, incoming and all edges?

Please see suggested "workaround" - does it represent the behaviour that you need in the end? (assuming that we count all incoming edges)
https://pizzabox.lynxanalytics.com/#/workspace/Users/olena.herasymenko@lynxanalytics.com/edge_aggregation
