### ISSUE TITLE
Visualization box: cannot remove (appears back), cannot add another visualization box (disappears), error shows Java.io.IOException: Operation not supported

### ISSUE THREAD

**Issue by sergii-zakharov** [lynxkite/lynxkite#274]
details:
  data:
    reference:
      customBoxStack: []
      top: 1_SERGII/1_Coexpression_network
    workspace:
      boxes:
        - id: anchor
          inputs: {}
          operationId: Anchor
          parameters: {}
          parametricParameters: {}
          x: 0
          'y': 0
        - id: SQL2_1
          inputs:
            one:
              boxId: Import-Parquet_1
              id: table
            two:
              boxId: Import-Parquet_2
              id: table
          operationId: SQL2
          parameters:
            persist: 'yes'
            sql: |-
              select least(gene1, gene2) as gene_1, 
                     greatest(gene1, gene2) as gene_2,
                     max(case when gene1=least(gene1, gene2) then n_coexpressed/n_expressed else 0 end) as p_expressed_cond_1_2,
                     max(case when gene2=least(gene1, gene2) then n_coexpressed/n_expressed else 0 end) as p_expressed_cond_2_1       
              from one
              left join two on one.gene1=two.Gene
              group by least(gene1, gene2), greatest(gene1, gene2)
          parametricParameters: {}
          x: 292.8228432548839
          'y': 295.3040382534978
        - id: SQL1_1
          inputs:
            input:
              boxId: SQL2_1
              id: table
          operationId: SQL1
          parameters:
            sql: |
              select 
                     min(p_expressed_cond_1_2), 
                     max(p_expressed_cond_1_2), 
                     min(p_expressed_cond_2_1), 
                     max(p_expressed_cond_2_1)       
                     from input
          parametricParameters: {}
          x: 464.1170107008644
          'y': 183.59593383804827
        - id: SQL1_2
          inputs:
            input:
              boxId: Import-Parquet_2
              id: table
          operationId: SQL1
          parameters:
            sql: |
              select min(n_expressed) from input
          parametricParameters: {}
          x: 300.0674022128019
          'y': 471.4460364650957
        - id: Use-table-as-graph_1
          inputs:
            table:
              boxId: SQL1_4
              id: table
          operationId: Use table as graph
          parameters:
            dst: gene_2
            src: gene_1
          parametricParameters: {}
          x: 795.6127749281443
          'y': 304.7829441350405
        - id: SQL1_3
          inputs:
            input:
              boxId: SQL2_1
              id: table
          operationId: SQL1
          parameters:
            sql: |
              select floor(p_expressed_cond_1_2*10)/10 as bin,
                     count(1)
              from input
              group by floor(p_expressed_cond_1_2*10)/10
              order by floor(p_expressed_cond_1_2*10)/10
          parametricParameters: {}
          x: 513.9585351982051
          'y': 452.3602201994631
        - id: SQL1_4
          inputs:
            input:
              boxId: SQL2_1
              id: table
          operationId: SQL1
          parameters:
            persist: 'yes'
            sql: >-
              select * 

              from input 

              where ((input.p_expressed_cond_1_2=1) and
              (input.p_expressed_cond_2_1<1)) or ((input.p_expressed_cond_2_1=1)
              and (input.p_expressed_cond_1_2<1))
          parametricParameters: {}
          x: 570.2161635463203
          'y': 307.1795555168647
        - id: SQL1_5
          inputs:
            input:
              boxId: SQL1_4
              id: table
          operationId: SQL1
          parameters:
            sql: |
              select count(1) from input
          parametricParameters: {}
          x: 719.6849699694944
          'y': 175.6197365680261
        - id: Aggregate-edge-attribute-to-vertices_1
          inputs:
            graph:
              boxId: Use-table-as-graph_1
              id: graph
          operationId: Aggregate edge attribute to vertices
          parameters:
            aggregate_gene_1: first
            direction: outgoing edges
            prefix: ''
          parametricParameters: {}
          x: 959.2912391913892
          'y': 257.69481221309496
        - id: Aggregate-edge-attribute-to-vertices_2
          inputs:
            graph:
              boxId: Aggregate-edge-attribute-to-vertices_1
              id: graph
          operationId: Aggregate edge attribute to vertices
          parameters:
            aggregate_gene_2: first
            direction: incoming edges
            prefix: ''
          parametricParameters: {}
          x: 1112.8510581402275
          'y': 311.9702654622534
        - id: Merge-two-vertex-attributes_1
          inputs:
            graph:
              boxId: Aggregate-edge-attribute-to-vertices_2
              id: graph
          operationId: Merge two vertex attributes
          parameters:
            attr2: gene_2_first
            name: gene
          parametricParameters: {}
          x: 1263.654405364439
          'y': 249.04865467633778
        - id: Discard-vertex-attributes_1
          inputs:
            graph:
              boxId: Merge-two-vertex-attributes_1
              id: graph
          operationId: Discard vertex attributes
          parameters:
            name: gene_1_first,gene_2_first,stringId
          parametricParameters: {}
          x: 1434.3753296038585
          'y': 316.7218138343058
        - id: Add-reversed-edges_1
          inputs:
            graph:
              boxId: Discard-vertex-attributes_1
              id: graph
          operationId: Add reversed edges
          parameters:
            distattr: if_reverse
          parametricParameters: {}
          x: 1582.0258586757893
          'y': 239.820496609342
        - id: Derive-edge-attribute_1
          inputs:
            graph:
              boxId: Compute-degree_1
              id: graph
          operationId: Derive edge attribute
          parameters:
            expr: if(if_reverse==0) p_expressed_cond_1_2 else p_expressed_cond_2_1
            output: p_expressed_cond
          parametricParameters: {}
          x: 1916.2739246946173
          'y': 218.20504236267743
        - id: Discard-edge-attributes_1
          inputs:
            graph:
              boxId: Derive-edge-attribute_1
              id: graph
          operationId: Discard edge attributes
          parameters:
            name: gene_1,gene_2,if_reverse,p_expressed_cond_1_2,p_expressed_cond_2_1
          parametricParameters: {}
          x: 2073.5181033374583
          'y': 340.88446287907016
        - id: Graph-visualization_2
          inputs:
            graph:
              boxId: Discard-edge-attributes_1
              id: graph
          operationId: Graph visualization
          parameters:
            state: >-
              {"left":{"projectPath":"","graphMode":"sampled","display":"svg","filters":{"vertex":{"degree":"","gene":"ACACA,ALDH1A1,AMACR,ANXA7,BMI1,BNIP3,CDKN3,CENPF,COPS5,CTNNA2,DDC,HJURP,FDPS,GSTA4,GSTM4,PFDN6,PGRMC1,CXCL8,IMPA2,MTFR1,RHOBTB3,ADIPOR1,IFT20,CHPT1,TMEM106C,NCOA2,NHP2,PAK4,PDCD5,PIR,PLA2G12B,PMVK,PPP2R5A,PEX2,RAB4A,SDC2,SDHC,SEMA5A,AURKA,TBCE,TBX3,HTATIP2,TNFAIP3,TOB1,TOP2A,TP53BP2,ZBTB18"},"edge":{}},"bucketCount":4,"preciseBucketSizes":false,"relativeEdgeDensity":false,"axisOptions":{"vertex":{},"edge":{}},"sampleRadius":0,"attributeTitles":{"label":"gene","size":"degree","edge
              color":"p_expressed_cond"},"animate":{"enabled":false,"style":"expand","labelAttraction":0},"centers":["197092596059741697","258464839746201668","689122967157738605","1412425988431685391","1454214598587593491","1764574639113116492","1800641210369454026","1851044348100087615","1938559847263908352","1963803685049869336","2374323629933467254","2609092267524228560","2677734202920674994","2882933438082462130","3018960515545182296","3526537538678296048","3598260846821652569","4065592411483539653","4427671267071508868","4484740722326512659","4974852097741694675","5021232813916045378","5046049813557157044","5087994945206226516","5210410296350351954","5443134976184823256","5539718409735908253","5687824631747061232","5867903990468972188","5888449159802921110","5972707673597024261","6268587627021077717","6272913578211158948","6291227739668097017","6409626471756738561","6605393701038465250","6651920742453618175","6803739173418182337","7012786059327054130","7125817456685233567","7468283335526069978","7472432643301182475","7568127804601011642","7739303919456627670","8965716373242130380","9057095959992863412"],"customVisualizationFilters":false,"vertexColorMap":"Viridis","labelColorMap":"Viridis","edgeColorMap":"Viridis","sliderColorMap":"Blue
              to
              orange","lastCentersRequest":{"count":47,"filters":[{"attributeName":"gene","valueSpec":"ACACA,ALDH1A1,AMACR,ANXA7,BMI1,BNIP3,CDKN3,CENPF,COPS5,CTNNA2,DDC,HJURP,FDPS,GSTA4,GSTM4,PFDN6,PGRMC1,CXCL8,IMPA2,MTFR1,RHOBTB3,ADIPOR1,IFT20,CHPT1,TMEM106C,NCOA2,NHP2,PAK4,PDCD5,PIR,PLA2G12B,PMVK,PPP2R5A,PEX2,RAB4A,SDC2,SDHC,SEMA5A,AURKA,TBCE,TBX3,HTATIP2,TNFAIP3,TOB1,TOP2A,TP53BP2,ZBTB18"}]},"lastCentersResponse":["197092596059741697","258464839746201668","689122967157738605","1412425988431685391","1454214598587593491","1764574639113116492","1800641210369454026","1851044348100087615","1938559847263908352","1963803685049869336","2374323629933467254","2609092267524228560","2677734202920674994","2882933438082462130","3018960515545182296","3526537538678296048","3598260846821652569","4065592411483539653","4427671267071508868","4484740722326512659","4974852097741694675","5021232813916045378","5046049813557157044","5087994945206226516","5210410296350351954","5443134976184823256","5539718409735908253","5687824631747061232","5867903990468972188","5888449159802921110","5972707673597024261","6268587627021077717","6272913578211158948","6291227739668097017","6409626471756738561","6605393701038465250","6651920742453618175","6803739173418182337","7012786059327054130","7125817456685233567","7468283335526069978","7472432643301182475","7568127804601011642","7739303919456627670","8965716373242130380","9057095959992863412"]},"right":{"display":"svg","filters":{"vertex":{},"edge":{}},"bucketCount":4,"preciseBucketSizes":false,"relativeEdgeDensity":false,"axisOptions":{"vertex":{},"edge":{}},"sampleRadius":1,"attributeTitles":{},"animate":{"enabled":false,"style":"expand","labelAttraction":0},"centers":["auto"],"customVisualizationFilters":false,"vertexColorMap":"Viridis","labelColorMap":"Viridis","edgeColorMap":"Viridis","sliderColorMap":"Blue
              to orange"}}
          parametricParameters: {}
          x: 2221.5262852251717
          'y': 217.96572973416642
        - id: Import-Parquet_1
          inputs: {}
          operationId: Import Parquet
          parameters:
            filename: >-
              dbfs:/sergii-lynx/1_Cytovia/data_lk/lk_n_coexpressed_GSE_Tumor_V2_mean_3std.parquet
            imported_table: 6d7cca99-e3f6-3af5-b18e-9140739e0846
            last_settings: |-
              {
                "sql" : "",
                "imported_columns" : "",
                "filename" : "dbfs:/sergii-lynx/1_Cytovia/data_lk/lk_n_coexpressed_GSE_Tumor_V2_mean_3std.parquet",
                "limit" : ""
              }
          parametricParameters: {}
          x: 180.34589359080022
          'y': 143.05040852753234
        - id: Import-Parquet_2
          inputs: {}
          operationId: Import Parquet
          parameters:
            filename: >-
              dbfs:/sergii-lynx/1_Cytovia/data_lk/lk_n_expressed_GSE_Tumor_V2_mean_3std.parquet
            imported_table: cb33d807-ed26-351d-8891-ba4137a020fd
            last_settings: |-
              {
                "sql" : "",
                "imported_columns" : "",
                "filename" : "dbfs:/sergii-lynx/1_Cytovia/data_lk/lk_n_expressed_GSE_Tumor_V2_mean_3std.parquet",
                "limit" : ""
              }
          parametricParameters: {}
          x: 81.8800315409683
          'y': 467.138100208146
        - id: Compute-degree_1
          inputs:
            graph:
              boxId: Add-reversed-edges_1
              id: graph
          operationId: Compute degree
          parameters:
            direction: all neighbors
          parametricParameters: {}
          x: 1727.4046496659507
          'y': 350.94648224740376
  request: ajax/setAndGetWorkspace
message: 'java.io.IOException: Operation not supported'
url: >-
  https://dbc-dp-622560398774279.cloud.databricks.com/driver-proxy/o/622560398774279/0831-010941-375ajn8d/2200/#/workspace/1_SERGII/1_Coexpression_network
version: ''

**Comment by darabos** [comment]
The metadata directory was on a filesystem that does not support append. It should be fixed now.
