### ISSUE TITLE
Unclear how to configure .kiterc with docker

### ISSUE THREAD

**Issue by krivachy** [lynxkite/lynxkite#31]
Using the docker getting started guide, I wasn't able to figure out how to configure a .kiterc file (e.g. `NEO4J_PASSWORD`).

It is referenced in the docs two places:
- https://lynxkite.com/docs/latest/user-guide/#installation
- https://lynxkite.com/docs/latest/admin-manual/#kiterc-file

Could the documentation be updated to explain how to configure these things when using Docker?

**Comment by darabos** [comment]
Thanks, that's a good point. Currently only some kiterc settings are exposed in Docker mode, those that are set in [docker/run.sh](https://github.com/lynxkite/lynxkite/blob/4.0.0/docker/run.sh). You can set these by controlling the Docker container's environment, as in `docker -e KITE_MASTER_MEMORY_MB=1024 lynxkite/lynxkite`.
 But I would also love to allow LynxKite to just take any setting from the environment variables.

A workaround until then is to change `/lynxkite/conf/kiterc_template` in the container. Either by changing the file inside, or by mounting an external file over it via `-v`.

**Comment by darabos** [comment]
Note from backlog triage:
- Let's remove the kiterc_overrides mechanism.
- Look at environment variables first, kiterc file second.
- Be sure to document this.
- Added to 4.1 milestone.

**Comment by xandrew-lynx** [comment]
For the record, the kiterc_template override trick doesn't work for variables directly overwritten in runner.sh:
https://github.com/lynxkite/lynxkite/blob/master/docker/run.sh#L8
If you need to change those then I think your only hope is to create your own version of runner.sh and mount it over the official one.
