### ISSUE TITLE
SIGINT doesn't terminate lynxkite docker container

### ISSUE THREAD

**Issue by krivachy** [lynxkite/lynxkite#32]
After running the getting started docker command (https://lynxkite.com/getting-started#docker-linux):

```
docker run \
  -p 2200:2200 \
  -v ~/lynxkite_meta:/metadata -v ~/lynxkite_data:/data \
  -e KITE_MASTER_MEMORY_MB=1024 \
  --name lynxkite lynxkite/lynxkite
```

Sending ctrl+c to the process doesn't stop it and needs to be done via docker kill/stop. While not a major it's a slight inconvenience when getting started.

**Comment by olahg** [comment]
Inserting an exec here: https://github.com/lynxkite/lynxkite/blob/main/tools/call_spark_submit.sh#L340 solves this, that is, change `"${command[@]}"` to `exec "${command[@]}"`

**Comment by darabos** [comment]
> Inserting an exec here: https://github.com/lynxkite/lynxkite/blob/main/tools/call_spark_submit.sh#L340 solves this, that is, change `"${command[@]}"` to `exec "${command[@]}"`

Thanks a lot! It's coming in https://github.com/lynxkite/lynxkite/pull/190.
