### ISSUE TITLE
Type inference doesn't work in "Create graph in python"

### ISSUE THREAD

**Issue by xandrew** [lynxkite/lynxkite#42]
Tested on demo, 4.0.1, using the example from the help.

**Comment by xandrew** [comment]
![Screenshot from 2020-07-03 11-10-45](https://user-images.githubusercontent.com/950033/86453528-4014e080-bd1e-11ea-83f7-20b42dde2704.png)

**Comment by darabos** [comment]
It works if you add an empty line at the start. (Which is how it is in the unit test!) Who would have thought parsing Python with a regex could have issues? 😄  The 4.0.1 release is not complete yet. I'll sneak in a fix for this.
