### ISSUE TITLE
Neo4j import/export operations need to be added to _import_box_names and _export_box_names in kite.py

### ISSUE THREAD

**Issue by xandrew-lynx** [lynxkite/lynxkite#98]
Maybe a test for the API use would also be nice...

**Comment by xandrew-lynx** [comment]
Workaround until next release if somebody hits this:
```
import lynx.kite
lk = lynx.kite.LynxKite()
lk._import_box_names.append('importFromNeo4j')
lk._export_box_names.append('exportVertexAttributesToNeo4j')
...
```

**Comment by darabos** [comment]
> Workaround until next release if somebody hits this:

We haven't made a 4.1.0 release of the Python package yet. We can definitely make one and include this. Do you have the code? (I've you calling it in the blog post.)

**Comment by xandrew-lynx** [comment]
Done by Dani in #99
